# Generated by Django 5.0.8 on 2024-08-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='flow',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.CharField(default='Novice', max_length=50),
        ),
    ]
