# Generated by Django 5.0.8 on 2024-08-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reward_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
