# Generated by Django 5.0.8 on 2024-08-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_rank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='max_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
