# Generated by Django 5.0.8 on 2024-08-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_rank', '0002_alter_rank_max_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
