# Generated by Django 5.0.8 on 2024-08-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_habit_user_alter_habitrecord_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitrecord',
            name='reward_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
