# Generated by Django 5.0.8 on 2024-08-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_remove_flowsession_duration_flowsession_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowsession',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
    ]
